---
title: "data preparation 6 - 10 / 3 / 2023"
output:
  pdf_document: default
---

# Objective
The purpose of this notebook is data preparation, namely: rename variables in English, remove special characters or whitespaces, create simple categorical variables to better represent the information, build a single `.csv` file.  

The code is written as a `function()` and applied to all source files `*.xlsx`.

```{r include=FALSE}
library(tidyverse)
library(readxl)
```
 
 
 
```{r}

prepare_for_analysis <- function(input_file, 
                                 selected_cols, 
                                 new_column_names){
  
  df <- read_excel(input_file)  %>% 
  
    # remove unnecessary columns
    select(all_of(selected_cols)) %>%
    
    # rename columns
    setNames(new_column_names) %>%
  
    #replace spaces with _ in column names
    rename_with(~ gsub(" ", "_", .), everything()) %>%
  
    #remove special characters such as ò, à ...
    mutate(across(where(is.character), ~ gsub("[^a-zA-Z0-9\\s]", " ", .))) %>%
    
    #set appropriate format for Day and get weekday
    mutate(day = as.Date(day, format = "%d-%m-%Y")) %>%
    mutate(weekday = as.numeric(format(day, "%u"))) %>%
    
    # encode direction as inbound or outbound
    mutate(direction = case_when(
      grepl("di ritorno da altro Comune", type) ~ "inbound",
      grepl("diretto in altro Comune", type) ~ "outbound",
      TRUE ~ "--")) %>%
    
    # encode type of traveller
    mutate(res_trav = case_when(
      grepl("Residente", type) ~ "resident",
      grepl("Viaggiatore", type) ~ "traveller",
      TRUE ~ "--")) 
    
    return(df)
}


```
 
select and rename columns:

```{r warning=FALSE}

  
selected_cols <-  c(
  "Giorno", "Comune di partenza", "Comune di arrivo", "Tipologia viaggiatore", "Viaggi",    "00-03", "03-06", "06-09", "09-12", "12-15", "15-18", "18-21", "21-24")

new_column_names <- c(
  "day", "origin", "destination", "type", "n", 
  "00_03", "03_06", "06_09", "09_12", "12_15", "15_18", "18_21", "21_24")

input_file <- './data/EXPORT FVG _ 6-10 MARZO 2023.xlsx'

df <- input_file %>% 
  prepare_for_analysis(selected_cols, new_column_names)  
  
print(df)
 
```

```{r}
# filter relevant rows
print("BEROFRE filtering:")
table(df$type)

#df <- df %>% filter(str_detect(type, "^Residente Comunale"))
df <- df %>% filter(res_trav == "resident")

print("AFTER filtering:")
table(df$type)
```

```{r}
df %>% write.csv("dati_6_10_marzo_2023.csv")
```


